name: Deploy Production {{ github.ref }}
on:
  workflow_dispatch:
env:
  APP_NAME: marketplace-service
  APP_BUILD_ID: ${{ github.ref_name }}
permissions:
  id-token: write
  issues: write
jobs:
  DeployProduction:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
